Pintaboard is a plugin for [[http://5digits.org/pentadactyl/][Pentadactyl]] that replaces the build-in
bookmarking storage with service to [[Pinboard.in]].


* Installation

  From [[http://5digits.org/pentadactyl/plugins][the pentadactyl plugin page]]: 

: Install these plugins by copying them to the  ~/.pentadactyl/plugins/ directory
: (or %USERPROFILE%\pentadactyl\plugins on Windows).
  
* Setup

  The setup is simple at this point. First, install the plugin as
  instructed above.  Next, you will need to provide your pinboard.in
  API token as a setting.

  This API token can be found on your settings/password page.  For
  more, see [[http://blog.pinboard.in/2012/07/api_authentication_tokens/][this blog post]].

  In your settings file, simply put:

: loadplugins '\.(js|penta)$'
: set pintaboardToken="<YourTokenHere>"

* Usage

  By default, it overrides the =a= shortcut for bookmarking. That
  means you can use it as you normally would with Pentadactyl
  bookmarking.

  The actual command called is =:pinbookmark= which takes one main
  argument -- the URL.  However, there are trhee options that it also
  takes.

  | Option | Value                        |
  |--------+------------------------------|
  | -desc  | Text string                  |
  | -tags  | Comma-separated list of tags |
  | -title | Page title                   |
  | -shared| shared or private            |
  | -toread| set as unread                |
  

  By default, the =a= key is mapped to run someting like the
  following:

: :pinbookmark -title='Current Page Title' http://URL

** Tags

   To add tags, type =a= and then a space followed by =-tags==. There
   is some tab-completion in pentadactyl that will shorten this
   behavior.

   Once you hit the trailing equals, there will be some suggested
   tags or stored tags available for completion. Tab-completion works
   here also.

   The only problem is that tags cannot contain spaces, but I'm not
   sure you would want multi-word tags anyhow.

** Description

   Like the other options, =-desc== lets you pass in a string (with
   quotes) describing the link. This maps to the description field in pinboard.

** Title

   This is not necessary to add if you are using the built-in
   shortcut. But, useful to know if the page title is not what you
   want to store in pinboard. The text here becomes the text for the
   link stored.

** Shared

   To make private, set =-shared== with a no, otherwise it'll be public.

** Toread

   Not needed, but will allow setting as unread using =-toread==yes. Use with a 
   mapping to allow for quick marking for later reading; e.g.:
    
    map -ex gR :pinbookmark -toread=yes
